name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend CI & Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run test
      - name: Deploy to Railway
        if: github.ref == 'refs/heads/main' && success() && steps.changes_backend.outputs.backend_changed == 'true'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up
    outputs:
      backend_changed: ${{ steps.changes_backend.outputs.backend_changed }}

  frontend:
    name: Frontend CI & Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci --legacy-peer-deps
      - run: npm run test
      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main' && success() && steps.changes_frontend.outputs.frontend_changed == 'true'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: npx vercel --prod --token $VERCEL_TOKEN --yes
    outputs:
      frontend_changed: ${{ steps.changes_frontend.outputs.frontend_changed }}